CREATE TABLE tasks (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  start_time TEXT NOT NULL,
  duration TEXT,
  category TEXT NOT NULL,
  streak INTEGER,
  start_date DATE,
  end_date DATE
)